# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: actuators.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='actuators.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0f\x61\x63tuators.proto\"\x08\n\x06\x41\x63tion\"\x18\n\x06Turned\x12\x0e\n\x06turned\x18\x01 \x01(\x08\"\x1c\n\nTempChange\x12\x0e\n\x06\x63hange\x18\x01 \x01(\t\"+\n\x0b\x41\x66terChange\x12\x0e\n\x06turned\x18\x01 \x01(\x08\x12\x0c\n\x04temp\x18\x02 \x01(\x05\x32u\n\x08\x41\x63tuator\x12\x1d\n\x07turn_on\x12\x07.Action\x1a\x07.Turned\"\x00\x12\x1e\n\x08turn_off\x12\x07.Action\x1a\x07.Turned\"\x00\x12*\n\x0b\x63hange_temp\x12\x0b.TempChange\x1a\x0c.AfterChange\"\x00\x62\x06proto3'
)




_ACTION = _descriptor.Descriptor(
  name='Action',
  full_name='Action',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=19,
  serialized_end=27,
)


_TURNED = _descriptor.Descriptor(
  name='Turned',
  full_name='Turned',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='turned', full_name='Turned.turned', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=29,
  serialized_end=53,
)


_TEMPCHANGE = _descriptor.Descriptor(
  name='TempChange',
  full_name='TempChange',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='change', full_name='TempChange.change', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=55,
  serialized_end=83,
)


_AFTERCHANGE = _descriptor.Descriptor(
  name='AfterChange',
  full_name='AfterChange',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='turned', full_name='AfterChange.turned', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='temp', full_name='AfterChange.temp', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=85,
  serialized_end=128,
)

DESCRIPTOR.message_types_by_name['Action'] = _ACTION
DESCRIPTOR.message_types_by_name['Turned'] = _TURNED
DESCRIPTOR.message_types_by_name['TempChange'] = _TEMPCHANGE
DESCRIPTOR.message_types_by_name['AfterChange'] = _AFTERCHANGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Action = _reflection.GeneratedProtocolMessageType('Action', (_message.Message,), {
  'DESCRIPTOR' : _ACTION,
  '__module__' : 'actuators_pb2'
  # @@protoc_insertion_point(class_scope:Action)
  })
_sym_db.RegisterMessage(Action)

Turned = _reflection.GeneratedProtocolMessageType('Turned', (_message.Message,), {
  'DESCRIPTOR' : _TURNED,
  '__module__' : 'actuators_pb2'
  # @@protoc_insertion_point(class_scope:Turned)
  })
_sym_db.RegisterMessage(Turned)

TempChange = _reflection.GeneratedProtocolMessageType('TempChange', (_message.Message,), {
  'DESCRIPTOR' : _TEMPCHANGE,
  '__module__' : 'actuators_pb2'
  # @@protoc_insertion_point(class_scope:TempChange)
  })
_sym_db.RegisterMessage(TempChange)

AfterChange = _reflection.GeneratedProtocolMessageType('AfterChange', (_message.Message,), {
  'DESCRIPTOR' : _AFTERCHANGE,
  '__module__' : 'actuators_pb2'
  # @@protoc_insertion_point(class_scope:AfterChange)
  })
_sym_db.RegisterMessage(AfterChange)



_ACTUATOR = _descriptor.ServiceDescriptor(
  name='Actuator',
  full_name='Actuator',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=130,
  serialized_end=247,
  methods=[
  _descriptor.MethodDescriptor(
    name='turn_on',
    full_name='Actuator.turn_on',
    index=0,
    containing_service=None,
    input_type=_ACTION,
    output_type=_TURNED,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='turn_off',
    full_name='Actuator.turn_off',
    index=1,
    containing_service=None,
    input_type=_ACTION,
    output_type=_TURNED,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='change_temp',
    full_name='Actuator.change_temp',
    index=2,
    containing_service=None,
    input_type=_TEMPCHANGE,
    output_type=_AFTERCHANGE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_ACTUATOR)

DESCRIPTOR.services_by_name['Actuator'] = _ACTUATOR

# @@protoc_insertion_point(module_scope)
